version: "3"
services:
  app:
    container_name: express-mongo
    build: .
    ports: 
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27107:27107"
